"""Ladekontext und Zeitfenster für flexible Verbraucher (Loxone, Config, Historie)."""
from __future__ import annotations

from optimizer.charging_schedule import (
    _align_like,
    _deadline_from_unix,
    _facade_loxone_ready_raw,
    _loxone_ready_deadline,
    _loxone_ready_raw,
    _window_start_for_day,
    apply_charging_window_constraints,
    charging_deadline_after,
    charging_schedule_enabled,
    config_day_schedule,
    consumer_charging_eligible_indices,
    deadline_from_ready_hour,
    hour_in_charging_window,
    matrix_charging_anchor,
    matrix_slot_datetime,
    next_scheduled_availability,
    parse_loxone_ready_by_time,
    parse_loxone_relative_ready_by,
    parse_loxone_time_hm,
    resolve_charging_deadline,
    schedule_day_key,
    schedule_indices_for_consumer,
)
from optimizer.charging_urgent import (
    URGENT_PLAN_KWH_EPSILON,
    asap_indices_for_urgent_min,
    hours_needed_to_deliver,
    latest_start_datetime,
    split_eligible_by_urgent_deadline,
    summarize_urgent_rule_usage,
    urgent_charging_indices,
    urgent_min_kwh_from_soc,
)
from optimizer.charging_resolve import (
    _config_path_apply_live_ist_soc,
    _config_path_with_plugged_in,
    _load_consumer_state_json,
    _load_open_charging_deadlines,
    _load_plug_cycle_fulfilled_flags,
    _loxone_absent_forecast_context,
    _loxone_inactive_context,
    _loxone_plugged_in_complete_context,
    _plugged_in_fulfilled_context,
    _resolve_config_path_charging_context,
    apply_horizon_charging_limits,
    apply_plug_cycle_fulfilled_contexts,
    fetch_loxone_charging_context,
    historical_charging_context,
    resolve_absent_availability,
    resolve_charging_context,
    resolve_charging_contexts,
    serialize_charging_contexts,
    suppresses_live_charging_output,
)

# Re-exports for tests that patch cc.<name> / cc.loxone_client
from integrations import loxone_client  # noqa: F401
from optimizer.ev_soc_tracking import (  # noqa: F401
    fetch_loxone_actual_soc_percent,
    loxone_reports_charge_complete,
)
from settings.ehal_marker_resolve import (  # noqa: F401
    resolve_get_evcs_limit_soc,
    resolve_get_evcs_soc_min_immediate,
)

# Re-Exports für API-Stabilität (from optimizer.charging_context import ...)
__all__ = [
    "URGENT_PLAN_KWH_EPSILON",
    "_align_like",
    "_config_path_apply_live_ist_soc",
    "_config_path_with_plugged_in",
    "_deadline_from_unix",
    "_facade_loxone_ready_raw",
    "_load_consumer_state_json",
    "_load_open_charging_deadlines",
    "_load_plug_cycle_fulfilled_flags",
    "_loxone_absent_forecast_context",
    "_loxone_inactive_context",
    "_loxone_plugged_in_complete_context",
    "_loxone_ready_deadline",
    "_loxone_ready_raw",
    "_plugged_in_fulfilled_context",
    "_resolve_config_path_charging_context",
    "_window_start_for_day",
    "apply_charging_window_constraints",
    "apply_horizon_charging_limits",
    "apply_plug_cycle_fulfilled_contexts",
    "asap_indices_for_urgent_min",
    "charging_deadline_after",
    "charging_schedule_enabled",
    "config_day_schedule",
    "consumer_charging_eligible_indices",
    "deadline_from_ready_hour",
    "fetch_loxone_actual_soc_percent",
    "fetch_loxone_charging_context",
    "historical_charging_context",
    "hour_in_charging_window",
    "hours_needed_to_deliver",
    "latest_start_datetime",
    "loxone_client",
    "loxone_reports_charge_complete",
    "matrix_charging_anchor",
    "matrix_slot_datetime",
    "next_scheduled_availability",
    "parse_loxone_ready_by_time",
    "parse_loxone_relative_ready_by",
    "parse_loxone_time_hm",
    "resolve_absent_availability",
    "resolve_charging_context",
    "resolve_charging_contexts",
    "resolve_charging_deadline",
    "resolve_get_evcs_limit_soc",
    "resolve_get_evcs_soc_min_immediate",
    "schedule_day_key",
    "schedule_indices_for_consumer",
    "serialize_charging_contexts",
    "split_eligible_by_urgent_deadline",
    "summarize_urgent_rule_usage",
    "suppresses_live_charging_output",
    "urgent_charging_indices",
    "urgent_min_kwh_from_soc",
]
