"""MILP-Verbraucher: Variablen, Liefer-Nebenbedingungen, Ergebnis-Extraktion."""
from __future__ import annotations

from .milp_consumer_vars import (
    _add_consumer_power_variables,
    _add_setpoint_power_variables,
    _consumer_power_at,
    _consumer_power_now,
    _consumer_powers_at,
    _consumer_powers_now,
    _consumer_pv_follow_at,
    _consumer_pv_follow_at_all,
    _consumer_pv_follow_now,
    _consumer_pv_follow_now_all,
    _flex_power_at_t,
    _min_on_hours,
    _planned_consumer_kwh,
    _planned_consumer_kwh_in_slots,
    add_generic_block_start_guard,
    add_generic_flex_rolling_constraints,
    add_min_on_time_constraints,
)
from .milp_consumer_delivery import (
    _add_consumer_delivery_constraints,
    _add_urgent_min_asap_constraint,
    _collect_urgent_rule_observability,
    _delivery_energy_expr,
    _eligible_slot_labels,
    _log_urgent_rule_observability,
    _max_deliverable_kwh,
    _parse_charging_deadline,
    delivery_constraint_diagnostics,
    filter_feasible_consumers,
)

# Re-Exports für API-Stabilität (from optimizer.milp_consumers import ...)
__all__ = [
    "_add_consumer_delivery_constraints",
    "_add_consumer_power_variables",
    "_add_setpoint_power_variables",
    "_add_urgent_min_asap_constraint",
    "_collect_urgent_rule_observability",
    "_consumer_power_at",
    "_consumer_power_now",
    "_consumer_powers_at",
    "_consumer_powers_now",
    "_consumer_pv_follow_at",
    "_consumer_pv_follow_at_all",
    "_consumer_pv_follow_now",
    "_consumer_pv_follow_now_all",
    "_delivery_energy_expr",
    "_eligible_slot_labels",
    "_flex_power_at_t",
    "_log_urgent_rule_observability",
    "_max_deliverable_kwh",
    "_min_on_hours",
    "_parse_charging_deadline",
    "_planned_consumer_kwh",
    "_planned_consumer_kwh_in_slots",
    "add_generic_block_start_guard",
    "add_generic_flex_rolling_constraints",
    "add_min_on_time_constraints",
    "delivery_constraint_diagnostics",
    "filter_feasible_consumers",
]
