name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true
        type: string

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok ${{ github.event.inputs.tag }}"
